Improve: Automatically determine PR review count from branch names.

diff --git a/bin/git-begin-review b/bin/git-begin-review
--- a/bin/git-begin-review
+++ b/bin/git-begin-review
@@ -8,6 +8,17 @@
 
 # USAGE: `git begin-review [{branch|PR-number}] [{remote}]`
 
+# - Typically, you'll run `git begin-review 1234` to create a local branch
+#   for another dev's branch that you want to review. Later, if that dev adds
+#   to their branch, and if that earlier review branch is the current branch,
+#   you can run `git begin-review` to create a new review branch for the same
+#   PR (indicated by the current branch name), which might be helpful to diff
+#   new changes against those you previously reviewed.
+#
+# - You can also (less commonly) create a review branch from a given branch
+#   name, and this command will attempt to retrieve the PR number associated
+#   with that branch (if there is just one, and not zero or two or more).
+
 # ***
 
 # CONVENTION: This is another of my (lb's) commands that follows some sort of
@@ -49,33 +60,56 @@
 #       # You can paste the branch, type dot-dot, paste again,
 #       # and then backspace once and increment the review counter.
 #       git diff <Ctrl-v>..<Ctrl-v><Backspace>2<CR>
+#
+#     MAYBE/2021-01-30: We could automate the diff using the latest
+#                       BRANCH_COUNT and comparing against the one
+#                       previous... but I'm not sure if it's worth
+#                       the time to implement.
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
-# YOU: Declare your own GITSMART_REVIEW_FORMAT via, e.g., ~/.bashrc, if you want.
+# YOU: Declare GITSMART_REVIEW_* environs if you want to customize branch name.
 
-_GS_BR_REVIEW_FMT='review${PR_DELIM}${PR_NUMBER}--${BRANCH_NAME}--${AUTHOR}${AU_DELIM}${DATE_NOW}-${DATE_COUNT}'
+_GS_BR_REVIEW_PREFIX='review${PR_DELIM}${PR_NUMBER}--${BRANCH_NAME}--${AUTHOR}${AU_DELIM}'
+_GS_BR_REVIEW_UNIQUE='${DATE_NOW}-${BRANCH_COUNT}'
 
-GITSMART_REVIEW_FORMAT="${GITSMART_REVIEW_FORMAT:-${_GS_BR_REVIEW_FMT}}"
+# Such that review branch named '${GITSMART_REVIEW_PREFIX}${GITSMART_REVIEW_UNIQUE}'
+GITSMART_REVIEW_PREFIX="${GITSMART_REVIEW_PREFIX:-${_GS_BR_REVIEW_PREFIX}}"
+GITSMART_REVIEW_UNIQUE="${GITSMART_REVIEW_UNIQUE:-${_GS_BR_REVIEW_UNIQUE}}"
+
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
+
+# 2021-01-30: (lb): Feeling lazy...
+REVIEW_PR_NUM=""
+REVIEW_REMOTE=""
+REVIEW_BRANCH=""
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
 git_begin_review () {
+  git_begin_review_init_particulars "$@" || exit $?
+
+  local review_branch="$(git_format_review_branch_name)"
+
+  # echo "Creating review branch: ${review_branch}"
+
+  git co -b "${review_branch}" "${REVIEW_REMOTE}/${REVIEW_BRANCH}"
+}
+
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
+
+git_begin_review_init_particulars () {
   local branch_or_pr_number="$1"
   local remote_or_empty="$2"
 
-  local remote=""
-  local branch=""
-
-  local pr_number=""
   if [ -z "${branch_or_pr_number}" ]; then
     # No arguments; try to get PR number from current branch name.
-    pr_number="$(git pr-number-from-branch-name)"
+    REVIEW_PR_NUM="$(git pr-number-from-branch-name)"
   else
-    pr_number="$(echo_number_or_empty_string "${branch_or_pr_number}")"
+    REVIEW_PR_NUM="$(echo_number_or_empty_string "${branch_or_pr_number}")"
   fi
 
-  if [ -z "${pr_number}" ] && [ -n "${branch_or_pr_number}" ]; then
+  if [ -z "${REVIEW_PR_NUM}" ] && [ -n "${branch_or_pr_number}" ]; then
     # Specified argument(s) should be specify branch (and maybe remote).
     # Or, single argument passed might specify both, e.g., remote/branch.
     local branch_after_remote=$( \
@@ -83,33 +117,33 @@ git_begin_review () {
       | sed -E 's/[^\/]*\/(.*)/\1/'
     )
     if [ "${branch_after_remote}" != "${branch_or_pr_number}" ]; then
-      remote=$( \
+      REVIEW_REMOTE=$( \
         echo "${branch_or_pr_number}" \
         | sed -E 's/([^\/]*)\/.*/\1/'
       )
-      if git_remote_exists "${remote}"; then
+      if git_remote_exists "${REVIEW_REMOTE}"; then
         # Slash found in branch name, and name before slash is valid remote.
-        branch="${branch_after_remote}"
+        REVIEW_BRANCH="${branch_after_remote}"
         # remote previously parsed and set.
       else
         # Slash in passed name, but not a recognized remote;
         # assumes slash happens to be in the branch name, and
         # uses remote (maybe) passes as second argument ($2).
-        branch="${branch_or_pr_number}"
+        REVIEW_BRANCH="${branch_or_pr_number}"
         # Will set remote later.
       fi
     else
       # No slash in passed name, so maybe remote at second argument ($2).
-      branch="${branch_or_pr_number}"
+      REVIEW_BRANCH="${branch_or_pr_number}"
       # Will set remote later.
     fi
   fi
 
   # ***
 
-  if [ -z "${pr_number}" ] && [ -z "${branch}" ]; then
+  if [ -z "${REVIEW_PR_NUM}" ] && [ -z "${REVIEW_BRANCH}" ]; then
     >&2 echo "USAGE: $(basename "$0") [{branch|PR-number}] [{remote}]"
-    exit 1
+    return 1
   fi
 
   # ***
@@ -117,73 +151,80 @@ git_begin_review () {
   # (lb) I don't see a way to tell `hub` which remote to use, other than
   # it deducing it from the existing repo remotes, so we'll just deduce
   # the same, and hopefully our remotes align.
-  if [ -z "${remote}" ]; then
-    remote="$(git lookup-remote "${remote_or_empty}")" || return $?
+  if [ -z "${REVIEW_REMOTE}" ]; then
+    REVIEW_REMOTE="$(git lookup-remote "${remote_or_empty}")" || return $?
   fi
 
   # ***
 
-  if [ -n "${pr_number}" ]; then
+  if [ -n "${REVIEW_PR_NUM}" ]; then
     # Get branch from PR.
-    must_define_hub
-    must_define_token
+    must_define_hub || return $?
+    must_define_token || return $?
     # Note: I checked the "official" `gh` command, but did not find
     # commands that I could use similar to what `hub` offers.
-    local remote_colon_branch="$(hub pr show -f %H ${pr_number} 2> /dev/null)"
+    local remote_colon_branch="$(hub pr show -f %H ${REVIEW_PR_NUM} 2> /dev/null)"
 
     if [ -z "${remote_colon_branch}" ]; then
-      >&2 echo "ERROR: No branch found for PR number: ${pr_number}"
-      hub pr show -f %H ${pr_number}
-      exit 1
+      >&2 echo "ERROR: No branch found for PR number: ${REVIEW_PR_NUM}"
+      >&2 echo "- Try: HUB_VERBOSE=1 hub pr show -f %H ${REVIEW_PR_NUM}"
+      return 1
     fi
 
-    remote=$(echo "${remote_colon_branch}" | sed -E 's/:.*$//')
-    branch=$(echo "${remote_colon_branch}" | sed -E 's/^.*://')
+    REVIEW_REMOTE=$(echo "${remote_colon_branch}" | sed -E 's/:.*$//')
+    REVIEW_BRANCH=$(echo "${remote_colon_branch}" | sed -E 's/^.*://')
 
-    if [ -z "${remote}" ] || [ -z "${branch}" ]; then
-      >&2 echo "ERROR: Unexpected $(hub pr show -f %H ${pr_number}) response: ${remote_colon_branch}"
-      exit 1
+    if [ -z "${REVIEW_REMOTE}" ] || [ -z "${REVIEW_BRANCH}" ]; then
+      >&2 echo "ERROR: Unexpected $(hub pr show -f %H ${REVIEW_PR_NUM}) response: ${remote_colon_branch}"
+      return 1
     fi
   else
-    # ${branch} is set. Try to deduce PR number (okay if cannot).
+    # ${REVIEW_BRANCH} is set. Try to deduce PR number (okay if cannot).
     if type hub > /dev/null 2>&1 && [ -n "${GITHUB_TOKEN}" ] ; then
       # FIXME/2021-01-30: (lb): Does this work without remote specified?
       #                         Or any differently?
-      #   local pr_numbers="$(hub pr list -f %I%n -b "${branch}")"
+      #   local pr_numbers="$(hub pr list -f %I%n -b "${REVIEW_BRANCH}")"
       # NOTE: There's a similar pr-show that includes newline (%n) by default.
       # FIXME/2021-01-30: How does pr-show handle multiple matches?
-      #   local pr_numbers="$(hub pr show -f %I -h "${remote}:${branch}")"
-      local pr_numbers="$(hub pr list -f %I%n -b "${remote}:${branch}")"
+      #   local pr_numbers="$(hub pr show -f %I -h "${remote}:${REVIEW_BRANCH}")"
+      local pr_numbers="$(hub pr list -f %I%n -b "${REVIEW_REMOTE}:${REVIEW_BRANCH}")"
       if [ -n "${pr_numbers}" ]; then
         if [ $(echo "${pr_numbers}" | wc -l) -gt 1 ]; then
           # HINT: To help debug `hub`:
-          #   HUB_VERBOSE=1 hub pr list -b "${remote}:${branch}" -f %I%
-          >&2 hub pr list -b "${remote}:${branch}" -f %I%
-          >&2 echo "hub pr list -b \"${remote}:${branch}\" -f %I%"
-          >&2 echo "WARNING: Unknown PR number: Multiple matches found for ${branch}."
+          #   HUB_VERBOSE=1 hub pr list -b "${REVIEW_REMOTE}:${REVIEW_BRANCH}" -f %I%
+          >&2 hub pr list -b "${REVIEW_REMOTE}:${REVIEW_BRANCH}" -f %I%
+          >&2 echo "hub pr list -b \"${REVIEW_REMOTE}:${REVIEW_BRANCH}\" -f %I%"
+          >&2 echo "WARNING: Unknown PR number: Multiple matches found for ${REVIEW_BRANCH}."
         else
-          pr_number="${pr_numbers}"
+          REVIEW_PR_NUM="${pr_numbers}"
         fi
       fi
     fi
   fi
 
-  # ***
+  # (lb): Kinda expected this to be necessary, but s'not:
+  #
+  #   export REVIEW_PR_NUM
+  #   export REVIEW_REMOTE
+  #   export REVIEW_BRANCH
+}
+
+git_format_review_branch_name () {
 
   # Refresh in case we need review branch to get author id.
-  git fetch "${remote}"
+  git fetch "${REVIEW_REMOTE}"
 
   # ***
 
-  local branch_ref="${remote}/${branch}"
+  local branch_ref="${REVIEW_REMOTE}/${REVIEW_BRANCH}"
 
   # Prefer the author's GH logon, which will be the most consistent
   # identifier. Fallback to using the author email, for no particular
   # reason.
   local author=""
-  if [ -n "${pr_number}" ]; then
+  if [ -n "${REVIEW_PR_NUM}" ]; then
     # %au is author (GitHub) login name.
-    author="$(hub pr show -f %au ${pr_number})"
+    author="$(hub pr show -f %au ${REVIEW_PR_NUM})"
   fi
   if [ -z "${author}" ]; then
     # Note that the Git log is easily manipulated, so neither name nor
@@ -204,21 +245,33 @@ git_begin_review () {
   local sep="-"
 
   local PR_NUMBER=""
-  [ -n "${pr_number}" ] && PR_NUMBER="${pr_number}" && PR_DELIM="${sep}"
+  [ -n "${REVIEW_PR_NUM}" ] && PR_NUMBER="${REVIEW_PR_NUM}" && PR_DELIM="${sep}"
 
-  local BRANCH_NAME="${branch}"
+  local BRANCH_NAME="${REVIEW_BRANCH}"
 
   local AUTHOR=""
   [ -n "${author}" ] && AUTHOR="${author}" && AU_DELIM="${sep}"
 
+  local review_prefix="$(eval printf "${GITSMART_REVIEW_PREFIX}")"
+
   local DATE_NOW="$(date "+%Y${sep}%m${sep}%d")"
 
-# FIXME/2021-01-30 17:30: Making this complicated now... or maybe a | sort is the tricket.
-  local DATE_COUNT=1
+  # (lb): Making this somewhat complicated now...
+  # Assumes the count component is always last.
 
-  local review_branch="$(eval printf "${GITSMART_REVIEW_FORMAT}")"
+  local last_count=$(
+    git rev-parse --abbrev-ref --branches="${review_prefix}*" \
+      | sed -E 's/^.*\-([[:digit:]]+)$/\1/' \
+      | sort -n -r \
+      | head -1
+  )
 
-  echo "${review_branch}"
+  BRANCH_COUNT=1
+  [ -n "${last_count}" ] && let 'BRANCH_COUNT = last_count + 1'
+
+  local review_unique="$(eval printf "${GITSMART_REVIEW_UNIQUE}")"
+
+  echo "${review_prefix}${review_unique}"
 }
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
@@ -227,7 +280,7 @@ must_define_hub () {
   type hub > /dev/null 2>&1 && return
 
   >&2 echo 'USAGE: Please install `hub` to get branch name from PR number.'
-  exit 1
+  return 1
 }
 
 must_define_token () {
@@ -237,7 +290,7 @@ must_define_token () {
   >&2 echo "- If you need a token, visit:"
   >&2 echo
   >&2 echo "    https://github.com/settings/tokens"
-  exit 1
+  return 1
 }
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
@@ -258,8 +311,14 @@ echo_number_or_empty_string () {
   echo "${number_or_empty}"
 }
 
+git_branch_exists () {
+  local branch_name="$1"
+  git show-ref --verify --quiet refs/heads/${branch_name}
+}
+
 git_remote_exists () {
   local remote="$1"
+
   git remote get-url ${remote} &> /dev/null
 }
 
