Harden: Don't allow git-edit or git-reword if staged changes

diff --git a/bin/git-edit b/bin/git-edit
--- a/bin/git-edit
+++ b/bin/git-edit
@@ -42,6 +42,12 @@ git_edit_revision () {
 
   set -e
 
+  if ! git diff --cached --quiet; then
+    >&2 echo "ERROR: git-edit disabled while staging"
+
+    return 1
+  fi
+
   local wipped=false
 
   git add -A \
diff --git a/bin/git-reword b/bin/git-reword
--- a/bin/git-reword
+++ b/bin/git-reword
@@ -19,6 +19,12 @@ git_reword_revision () {
 
   set -e
 
+  if ! git diff --cached --quiet; then
+    >&2 echo "ERROR: git-reword disabled while staging"
+
+    return 1
+  fi
+
   local wipped=false
 
   git add -A \
