Feature: Cleanup git-fup using todo 'exec'; run 'exec' on git-abort

diff --git a/bin/git-abort b/bin/git-abort
--- a/bin/git-abort
+++ b/bin/git-abort
@@ -1,4 +1,43 @@
 #!/usr/bin/env bash
+# vim:tw=0:ts=2:sw=2:et:norl:ft=bash
+# Author: Landon Bouma (landonb &#x40; retrosoft &#x2E; com)
+# Project: https://github.com/landonb/git-smart#💡
+# License: MIT. Please find more in the LICENSE file.
+
+# USAGE:
+#   git rebase ...
+#   # Decide you want to `git rebase --abort`
+#   git abort
+#
+# Also works during cherry-pick, merge, and revert operations.
+#
+# UCASE: This command is especially helpful if you normally use
+# a rebase todo 'exec' action to cleanup after a rebase, because
+# that 'exec' won't run if you `git rebase --abort` the rebase.
+# - So if you always abort via git-abort (and not `git rebase --abort`),
+#   then you'll be assured that any post-rebase hooks that might
+#   otherwise not run will run.
+#   - See the git-fup command for real-world usage. It uses an
+#     'exec' to pop the WIP commit, and to restage the "fixup!"
+#     commit. And it uses the #git-abort tag (see below) to tell
+#     git-abort to run the 'exec' if the user aborts the rebase.
+
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
+
+# This is the known Git rebase todo path.
+# - SPIKE: Can we get this from `git` so it's not hardcoded?
+GIT_REBASE_TODO_PATH=".git/rebase-merge/git-rebase-todo"
+
+# This is the special tag at the end of the 'exec' line that
+# you must use if you git-abort to run that 'exec'.
+# - USYNC: This environ is used in git-smart and tig-newtons.
+GITSMART_POST_REBASE_EXECS_TAG=" #git-abort"
+
+# This is an intermediate path git-abort uses to cache the
+# 'exec' lines, before `git rebase --abort` removes the todo.
+GITSMART_POST_REBASE_EXECS_PATH=".git/git-smart-git-abort-post-rebase-execs"
+
+# ***
 
 git_abort () {
   local gitdir
@@ -28,6 +67,8 @@ git_abort () {
   git_abort_try "${opfound}" "${fcnt}" "${plumbing_files}"
 }
 
+# ***
+
 git_abort_try () {
   local opfound="$1"
   local fcnt="$2"
@@ -54,8 +95,72 @@ git_abort_try () {
     exit 1
   fi
 
+  git_abort_post_rebase_execs_cache "${opfound}"
+
+  local retcode
+
   git ${opfound} --abort
+  retcode=$?
+
+  if [ ${retcode} -eq 0 ]; then
+    git_abort_post_rebase_execs_run_maybe
+  fi
+
+  git_abort_post_rebase_execs_cleanup
+
+  return ${retcode}
 }
+
+# ***
+
+# Assumes any 'exec' tagged with #git-abort should be run on abort.
+# - In practice, these 'exec' will follow all the commit actions.
+#   But it's not worth our effort to be strict about it. Also the
+#   tag itself says it all, run this commit on abort.
+git_abort_post_rebase_execs_cache () {
+  local opfound="$1"
+
+  command rm -f "${GITSMART_POST_REBASE_EXECS_PATH}"
+
+  # The #git-abort 'exec' magic only applies to rebase,
+  # which is the only action that uses a todo file.
+  if [ "${opfound}" != "rebase" ]; then
+    return
+  fi
+
+  if [ ! -e "${GIT_REBASE_TODO_PATH}" ]; then
+    # Unreachable, unless Git changes rebase-todo path or something.
+    >&2 echo "ALERT: Expected to find rebase-todo (for ‘${opfound}’) at:"
+    >&2 echo "  ${GIT_REBASE_TODO_PATH}"
+
+    return
+  fi
+
+  # Look for special #git-abort tag and only cache those exec calls.
+  grep -e "^exec .*${GITSMART_POST_REBASE_EXECS_TAG}$" "${GIT_REBASE_TODO_PATH}" \
+    > "${GITSMART_POST_REBASE_EXECS_PATH}"
+}
+
+git_abort_post_rebase_execs_cleanup () {
+  command rm -f "${GITSMART_POST_REBASE_EXECS_PATH}"
+}
+
+git_abort_post_rebase_execs_run_maybe () {
+  [ -s "${GITSMART_POST_REBASE_EXECS_PATH}" ] \
+    || return
+
+  while read pre_line; do
+    local post_rebase_exec="${pre_line#exec }"
+
+    # Git prints "Executing: <exec>" for each 'exec', as do we.
+    echo "Executing: ${post_rebase_exec}"
+
+    # So trustworthy.
+    eval ${post_rebase_exec}
+  done < <(cat "${GITSMART_POST_REBASE_EXECS_PATH}")
+}
+
+# ***
 
 git_abort
 
diff --git a/bin/git-fup b/bin/git-fup
--- a/bin/git-fup
+++ b/bin/git-fup
@@ -24,6 +24,15 @@
 
 GITSMART_GIT_FUP_WIP_COMMIT_MESSAGE="${PRIVATE_PREFIX:-PRIVATE: }WIP [git-fup]"
 
+# This is the known Git rebase todo path.
+# - SPIKE: Can we get this from `git` so it's not hardcoded?
+GIT_REBASE_TODO_PATH=".git/rebase-merge/git-rebase-todo"
+
+# This is the special tag at the end of the 'exec' line that
+# you must use if you git-abort to run that 'exec'.
+# - USYNC: This environ is used in git-smart and tig-newtons:
+GITSMART_POST_REBASE_EXECS_TAG=" #git-abort"
+
 git_fixup_and_rebase () {
   local commit="$1"
 
@@ -65,15 +74,41 @@ git_fixup_and_rebase () {
     # we'll just remind user about the WIP commit; otherwise we can take
     # the time to add code to prompt-loop until .git/REBASE_HEAD gone.
     print_error_rebase_failed_shared
-    if ${pop_after}; then
-      print_error_rebase_failed_wipped
-    fi
 
     rebase_failed=true
   fi
 
-  if ${pop_after} && ! ${rebase_failed}; then
-    # Unnecessary and unnecessarily complex state check.
+  if ${rebase_failed}; then
+    # This feels a little... backhanded. Or maybe just sneaky.
+    #
+    # Append rebase-todo with 'exec' cleanup commands:
+    # - Pop the WIP, if we used one (with `git reset --mixed @~1`).
+    # - Restage the fixup! (with `git reset --soft @~1`, aka `git undo`).
+    #   - This restages the intermediate commit the `--fixup` created,
+    #     titled like "fixup! <target commit message>". So the user
+    #     can now endlessly loop git-fup, git-abort, git-fup, etc.
+    # - Also sleep first and background `&` the 'exec', so that
+    #   git-rebase does not see uncommitted changes (otherwise it
+    #   thinks the rebase failed).
+    # - Finally, the #git-abort tag tells git-abort to run the execs
+    #   if the user aborts the rebase instead of finishing it.
+    # (At this point, it feels like we should just use a sequence editor
+    #  and write the initial todo ourselves. But there's also nothing that
+    #  says we shouldn't do it this way, and it works. Just hopping on the
+    #  party train a little late.)
+
+    local git_pop_wip=""
+    if ${pop_after}; then
+      git_pop_wip="git reset --mixed @~1 > /dev/null &&"
+    fi
+
+    echo "exec sleep 0.1 &&" \
+      "${git_pop_wip}git reset --soft @~1 & ${GITSMART_POST_REBASE_EXECS_TAG}" \
+        >> "${GIT_REBASE_TODO_PATH}"
+  elif ${pop_after}; then
+    # Rebase succeeded without user intervention. We are clear to
+    # pop the WIP commit... but we'll slide in an unnecessary and
+    # unnecessarily complex state check first just to be paranoid.
     double_triple_quadruple_check_rebase_complete \
       || exit 1
 
@@ -103,13 +138,12 @@ maybe_commit_uncommitted () {
 
 print_error_rebase_failed_shared () {
   >&2 echo
-  >&2 echo "ERROR: The rebase failed."
-}
-
-print_error_rebase_failed_wipped () {
-  >&2 echo "- You'll find the WIP commit we made after you finish rebasing."
-  >&2 echo "  You can easily remove this commit:"
-  >&2 echo "    git-pop1 { git reset --mixed @~1; }"
+  >&2 echo "ERROR: The git-fup rebase failed."
+  >&2 echo "- Hint: Resolve conflicts and run \`git rc\`" \
+    "(or \`git rebase --continue\`)"
+  >&2 echo "        Or, give up using \`git abort\`" \
+    "(a fancy \`git rebase --abort\`"
+  >&2 echo "        that restages your changes)"
 }
 
 # ***
