Improve: Simplify insist-run-via-Bash check
- Also, Improve: Return non-zero when check fails

diff --git a/bin/git-rebase-bubble-commit b/bin/git-rebase-bubble-commit
--- a/bin/git-rebase-bubble-commit
+++ b/bin/git-rebase-bubble-commit
@@ -154,18 +154,26 @@ git_rebase_buble_commit_noninteractive () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
-PROG_NAME="git-rebase-bubble-commit"
+insist_run_via_bash () {
+  local prog_name="$(basename -- "$0")"
+
+  # Complain if sourced (from any shell), or not run via Bash.
+  if [ -z "${BASH_SOURCE}" ] || [ "$0" != "${BASH_SOURCE[0]}" ]; then
+    >&2 echo "ERROR: Run this script with Bash [${prog_name}]"
+
+    return 1
+  fi
+}
+
+# ***
 
 main () {
   git_rebase_bubble_commit "$@"
 }
 
-# Complain if sourced (from any shell), or not run via Bash.
-if [ -z "${BASH_SOURCE}" ] || [ "$0" != "${BASH_SOURCE[0]}" ]; then
-  >&2 echo "ERROR: Run this script with Bash [${PROG_NAME}]"
-
-  false
-else
+if insist_run_via_bash; then
   main "$@"
+else
+  false
 fi
 
